name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-and-test:
    name: ${{ matrix.os }} with Zig ${{ matrix.zig-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        zig-version: [0.13.0]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: ${{ matrix.zig-version }}

      - name: Zig version
        run: zig version

      - name: Build
        run: zig build

      - name: Run tests
        run: zig build test | tee test-results.txt
      
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.os }}
          path: test-results.txt

      - name: Run example
        run: zig build run
        continue-on-error: true  # Won't fail the workflow if network requests fail
